# Beispiel zu den linearen Operatoren

In [1]:
import numpy as np

Betrachte die Abbildung $A: \mathbb{R}^n \to \mathbb{R}^m$ gegeben durch eine zufällige Matrix $\mathbb{R}^{m\times n}$:

In [2]:
n = 3
m = 5

A = np.random.randint(-9,9,size=(m,n))

In [3]:
A

array([[ 0, -4, -3],
       [-6, -1,  1],
       [ 4,  2,  2],
       [-7,  0,  4],
       [ 3,  2, -6]])

Für die Operatornorm, hier in dem Fall konkret, der Matrix-Norm erhalten wir:

## Maximum Norm

In [4]:
# max-Norm
np.linalg.norm(A,np.inf)

11.0

Die Max-(Matrix-)Norm ist gegeben durch das Maximum der absoluten Zeilensummen:

In [5]:
np.sum(np.abs(A),axis=1)

array([ 7,  8,  8, 11, 11])

## 1-Norm

In [6]:
# max-Norm
np.linalg.norm(A,1)

20.0

Die 1-(Matrix-)Norm ist gegeben durch das Maximum der absoluten Spaltensummen:

In [7]:
np.sum(np.abs(A),axis=0)

array([20,  9, 16])

## 2-Norm

In [8]:
# max-Norm
np.linalg.norm(A,2)

11.802937127483764

Die 2-(Matrix-)Norm ist gegeben durch den grössen Eigenwert von $A^T\cdot A$:

In [9]:
np.linalg.eigvals(A.T@A)**(1/2)

array([11.80293713,  6.78441307,  3.95757683])